package com.example.recipefinder.presentation.util

import com.example.recipefinder.domain.model.MealClient

fun getIngredients(meal:MealClient):String{
    val result = StringBuilder()
    with(meal){
        if(!mealIngredient1.isNullOrEmpty())
            result.append("$mealIngredient1 - $mealMeasure1\n")
        if(!mealIngredient2.isNullOrEmpty())
            result.append("$mealIngredient2 - $mealMeasure2\n")
        if(!mealIngredient3.isNullOrEmpty())
            result.append("$mealIngredient3 - $mealMeasure3\n")
        if(!mealIngredient4.isNullOrEmpty())
            result.append("$mealIngredient4 - $mealMeasure4\n")
        if(!mealIngredient5.isNullOrEmpty())
            result.append("$mealIngredient5 - $mealMeasure5\n")
        if(!mealIngredient6.isNullOrEmpty())
            result.append("$mealIngredient6 - $mealMeasure6\n")
        if(!mealIngredient7.isNullOrEmpty())
            result.append("$mealIngredient7 - $mealMeasure7\n")
        if(!mealIngredient8.isNullOrEmpty())
            result.append("$mealIngredient8 - $mealMeasure8\n")
        if(!mealIngredient9.isNullOrEmpty())
            result.append("$mealIngredient9 - $mealMeasure9\n")
        if(!mealIngredient10.isNullOrEmpty())
            result.append("$mealIngredient10 - $mealMeasure10\n")
        if(!mealIngredient11.isNullOrEmpty())
            result.append("$mealIngredient11 - $mealMeasure11\n")
        if(!mealIngredient12.isNullOrEmpty())
            result.append("$mealIngredient12 - $mealMeasure12\n")
        if(!mealIngredient13.isNullOrEmpty())
            result.append("$mealIngredient13 - $mealMeasure13\n")
        if(!mealIngredient14.isNullOrEmpty())
            result.append("$mealIngredient14 - $mealMeasure14\n")
        if(!mealIngredient15.isNullOrEmpty())
            result.append("$mealIngredient15 - $mealMeasure15\n")
        if(!mealIngredient16.isNullOrEmpty())
            result.append("$mealIngredient16 - $mealMeasure16\n")
        if(!mealIngredient17.isNullOrEmpty())
            result.append("$mealIngredient17 - $mealMeasure17\n")
        if(!mealIngredient18.isNullOrEmpty())
            result.append("$mealIngredient18 - $mealMeasure18\n")
        if(!mealIngredient19.isNullOrEmpty())
            result.append("$mealIngredient19 - $mealMeasure19\n")
        if(!mealIngredient20.isNullOrEmpty())
            result.append("$mealIngredient20 - $mealMeasure20\n")
    }
    return result.toString().trimEnd('\n')
}